### ISSUE TITLE
Bearcart and iPython

### ISSUE THREAD

**Issue by wrobstory** [wrobstory/bearcart#1]
Bearcart _needs_ to be in iPython. But after some limited tinkering, I can't figure out how to load local JavaScript. 

Anyone?

**Comment by agconti** [comment]
Hi Rob, 

I think your project is great and would like to help you implement it into an IPython Notebook. Have you made any progress since this post?  Perhaps we could chat about a good place to start

**Comment by wrobstory** [comment]
Thanks! and no, I haven't- partially because there is so much change happening right now with iPython and rendering javascript in the notebook. These threads are a good indication of what's happening right now: 

http://python.6.x6.nabble.com/repr-javascript-code-samples-for-D3-td5016336.html
http://python.6.x6.nabble.com/implementing-sympy-plots-with-d3-in-the-notebook-td5017972.html

That's why I'm a little hesitant to start building- I'm afraid that things are going to change and break all of my work in just a few months. It actually sounds like they might build Bearcart and Vincent-like functionality right into iPython, which would be awesome, but would also kind of depreciate my tools :)

But, if you want to take a shot at it, I would love to have an interim solution.

**Comment by agconti** [comment]
Ahh the IPython dev team is always up to something cool. I might take a look in the meantime, but ill probably hold off until July. If they don't implement it, I'll definitely come back and take a closer look.

**Comment by wrobstory** [comment]
Closing this for now:

http://mail.scipy.org/pipermail/ipython-dev/2013-June/011764.html

I'm going to move for the next version of Bearcart to operate over JSON, if at all possible, so that integration with iPython can perhaps be trivial. Stay tuned.

**Comment by westurner** [comment]
@wrobstory

https://github.com/ipython/ipython/wiki/Roadmap:-IPython

https://en.wikipedia.org/wiki/Separation_of_presentation_and_content (JSON)

https://github.com/trifacta/vega/wiki/Documentation#overview

https://github.com/wrobstory/vincent/blob/master/vincent/ipynb.py

... feature overlap?

**Comment by wrobstory** [comment]
Maybe. I actually wrote Bearcart post-Vincent, because I wanted a really easy way to generate Rickshaw graphs with all of the dynamic widgets. I haven't spent much time on this lib, but do eventually want to JSON-ize it. I think that having declarative visualization specifications is generally a really good thing.

**Comment by westurner** [comment]
> I actually wrote Bearcart post-Vincent, because I wanted a really easy way to generate Rickshaw graphs with all of the dynamic widgets.

The Rickshaw graphs are great; thanks!

> I haven't spent much time on this lib, but do eventually want to JSON-ize it. I think that having declarative visualization specifications is generally a really good thing.

http://cwe.mitre.org/top25/#CWE-79

**Comment by wrobstory** [comment]
It's certainly a concern, and highlights the need to validate your specs and be careful about passing JSON messages via HTTP.

**Comment by westurner** [comment]
Absolutely.
