### ISSUE TITLE
Bearcart Notebook Initialization error in iPython Notebook

### ISSUE THREAD

**Issue by murphymj** [wrobstory/bearcart#11]
I keep running into this error and, as someone new to iPython specifically and rather new to Python in general, I haven't been able to nail down the source.

Right from the start when it reads this line: "bearcart.initialize_notebook()" I get this.
AttributeError: 'module' object has no attribute 'initialize_notebook'

I have seen it both when running the example notebook in the bearcart download as well as running the file from "Up and Down the Python Data and Web Visualization Stack" folder.

Any help would be appreciated as the demo from your talk made its handling of time series data very interesting.

**Comment by ahane** [comment]
it seems like the version available through the python package index PyPI is outdated and doesn't include the initialize_notebook method yet.
uninstalling bearcart with
`pip uninstall bearcart`
and re-installing directly from github:
`pip install git+git://github.com/wrobstory/bearcart.git`
fixed the issue for me.

**Comment by murphymj** [comment]
Thanks, that seems to have fixed the issue.
