### ISSUE TITLE
Example #1 gives error

### ISSUE THREAD

**Issue by nipunbatra** [wrobstory/bearcart#2]
I copied example number 1 as it is and got the following traceback.
NB: I printed Pandas DF to see if data were coming right or not

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 754 entries, 2010-01-04 00:00:00 to 2012-12-31 00:00:00
Data columns:
AAPL    754  non-null values
GOOG    754  non-null values
dtypes: float64(2)
Traceback (most recent call last):
  File "abc.py", line 23, in <module>
    vis = bearcart.Chart(price)
  File "/usr/local/lib/python2.7/dist-packages/bearcart/bearcart.py", line 101, in **init**
    self.transform_data(data)
  File "/usr/local/lib/python2.7/dist-packages/bearcart/bearcart.py", line 138, in transform_data
    elif (isinstance(objs['x'], pd.tslib.Timestamp) or
AttributeError: 'module' object has no attribute 'tslib'

**Comment by wrobstory** [comment]
Hm, interesting. Which version of Pandas are you using?

**Comment by nipunbatra** [comment]
I am using 0.8.0
Is it some API change in newer Pandas?

**Comment by wrobstory** [comment]
It very well could be- bearcart was developed on Pandas 0.10.1. Maybe make the upgrade, and then if you're still getting an error we'll try to figure out what's happening?

**Comment by nipunbatra** [comment]
With 0.11 it works well!

**Comment by wrobstory** [comment]
Great! Please let me know if you have any other issues (or feature suggestions!)
